version: "3.4"

services:
  node1:
    image: ddoop
    environment:
      NODES: node1:8000,node2:8000,node3:8000
      SELF_ID: node1:8000
    ports:
      - 9000:9000

  node2:
    image: ddoop
    environment:
      NODES: node1:8000,node2:8000,node3:8000
      SELF_ID: node2:8000
    ports:
      - 9001:9000

  node3:
    image: ddoop
    environment:
      NODES: node1:8000,node2:8000,node3:8000
      SELF_ID: node3:8000
    ports:
      - 9002:9000